"""Loads shopping_list.yaml, catalog.yaml and stores.yaml into typed objects."""

from __future__ import annotations

from pathlib import Path

import yaml

from .models import CatalogItem, FieldMapping, FulfillmentOption, ShoppingItem, StoreConfig


def load_shopping_list(path: Path) -> list[ShoppingItem]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return [
        ShoppingItem(
            name=item["name"],
            quantity=item.get("quantity", 1.0),
            unit=item.get("unit", "each"),
            aliases=item.get("aliases", []),
            notes=item.get("notes", ""),
        )
        for item in data["items"]
    ]


def load_catalog(path: Path) -> list[CatalogItem]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return [
        CatalogItem(
            name=item["name"],
            unit=item.get("unit", "each"),
            default_quantity=item.get("default_quantity", 1.0),
            aliases=item.get("aliases", []),
            manual_prices=item.get("manual_prices", {}),
        )
        for item in data["items"]
    ]


SHOPPING_LIST_HEADER = (
    "# Generated by grocery_scraper (select_items.py or webui.py) - "
    "don't hand-edit, regenerate instead.\n"
)

CATALOG_HEADER = (
    "# Your master product catalog - everything you might buy, not just this\n"
    "# week's list. Managed via `python -m grocery_scraper.webui` (or hand-edit -\n"
    "# saving from the web UI will strip per-item comments, just not this header).\n"
    "#\n"
    "# manual_prices: prices you've noted yourself for stores with no working\n"
    "# scraper (currently just Iceland). Update these whenever you shop there.\n"
)


def save_shopping_list(path: Path, items: list[ShoppingItem]) -> None:
    data = {
        "items": [
            {"name": i.name, "quantity": i.quantity, "unit": i.unit, "aliases": i.aliases}
            for i in items
        ]
    }
    path.write_text(SHOPPING_LIST_HEADER + yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def save_catalog(path: Path, items: list[CatalogItem]) -> None:
    data = {
        "items": [
            {
                "name": i.name,
                "unit": i.unit,
                "default_quantity": i.default_quantity,
                "aliases": i.aliases,
                "manual_prices": i.manual_prices,
            }
            for i in items
        ]
    }
    path.write_text(CATALOG_HEADER + yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def _fulfillment_from_dict(d: dict) -> FulfillmentOption:
    return FulfillmentOption(
        kind=d["kind"],
        available=d.get("available", True),
        fee=d.get("fee", 0.0),
        free_over=d.get("free_over"),
        surcharge_under=d.get("surcharge_under"),
        surcharge_amount=d.get("surcharge_amount", 0.0),
        verified=d.get("verified", False),
        notes=d.get("notes", ""),
    )


def load_stores(path: Path) -> list[StoreConfig]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    stores = []
    for s in data["stores"]:
        fields_dict = s.get("fields", {})
        stores.append(
            StoreConfig(
                name=s["name"],
                enabled=s.get("enabled", True),
                manual=s.get("manual", False),
                apify_actor_id=s.get("apify_actor_id"),
                apify_search_field=s.get("apify_search_field", "searchTerms"),
                apify_extra_input=s.get("apify_extra_input", {}),
                apify_data_root=s.get("apify_data_root"),
                fields=FieldMapping(
                    name=fields_dict.get("name", "title"),
                    price=fields_dict.get("price", "price"),
                    unit_price=fields_dict.get("unit_price", "unitPrice"),
                    in_stock=fields_dict.get("in_stock", "inStock"),
                ),
                fulfillment=[_fulfillment_from_dict(f) for f in s.get("fulfillment", [])],
                notes=s.get("notes", ""),
            )
        )
    return stores
